name: "infra preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - 10_infra/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: latest
  AWS_REGION: ap-northeast-1
  TF_VAR_aws_role_arn: ${{secrets.AWS_IAM_ROLE_ARN}}
  

defaults:
  run:
    shell: bash
    working-directory: "10_infra/"

jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: prepare aws
        run: |
          aws configure set region ap-northeast-1 --profile terraform && aws configure set aws_access_key_id ${{secrets.ACCESS_KEY_ID}} --profile terraform && aws configure set aws_secret_access_key ${{secrets.ACCESS_KEY}} --profile terraform
      - name: Checkout repos
        uses: actions/checkout@v3
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_versions: ${{ env.TF_VERSION}}
      - name: Terraform format
        run: |
          terraform fmt -check
      - name: Configure AWS Credential
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_IAM_ROLE_ARN}}
      - name: Terraform init
        run: |
          terraform init -no-color